# Generated by Django 4.0.6 on 2022-07-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipam', '0057_created_datetimefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nome_pool', models.CharField(max_length=200)),
                ('AllowNat', models.CharField(max_length=200)),
                ('AllowSNat', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=2000, null=True, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('verify', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='Pool_membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_membro', models.CharField(max_length=200)),
                ('fk_NODE_node_membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.pool')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Node_name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(default='active', max_length=200)),
                ('fk_NETBOX_IpAdress', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.ipaddress')),
            ],
        ),
    ]
