# Generated by Django 4.0.6 on 2022-08-02 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipam', '0057_created_datetimefield'),
        ('dcim', '0153_created_datetimefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(default='active', max_length=200)),
                ('fk_Netbox_ipaddress', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.ipaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_pool', models.CharField(max_length=200)),
                ('allownat', models.CharField(max_length=200)),
                ('allowsnat', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['nome_pool'],
            },
        ),
        migrations.CreateModel(
            name='VirtualAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ip_virtual_address', models.CharField(max_length=200)),
                ('partition', models.CharField(max_length=200)),
                ('campo', models.CharField(max_length=200)),
                ('fk_Node_node_nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.node')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('virtual_server_name', models.CharField(max_length=200)),
                ('mask', models.CharField(max_length=200)),
                ('porta', models.CharField(max_length=200)),
                ('fk_Pool_nome_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.pool')),
                ('fk_VirtualAddress_ip_virtual_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.virtualaddress')),
            ],
        ),
        migrations.CreateModel(
            name='PoolMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_membro', models.CharField(max_length=200)),
                ('fk_Node_node_nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.node')),
            ],
            options={
                'ordering': ['nome_membro'],
            },
        ),
        migrations.AddField(
            model_name='pool',
            name='fk_PoolMembro_nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.poolmembro'),
        ),
        migrations.CreateModel(
            name='ClusterBig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nome_cluster', models.CharField(max_length=200)),
                ('fk_Netbox_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.device')),
                ('fk_Node_node_nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.node')),
                ('fk_VirtualServer_virtual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.virtualserver')),
            ],
        ),
    ]
