# Generated by Django 4.0.6 on 2022-07-31 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0153_created_datetimefield'),
        ('bigipnetbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Virtual_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pk_virtual_addess', models.CharField(max_length=200)),
                ('ip_virtual_address', models.CharField(max_length=200)),
                ('partition', models.CharField(max_length=200)),
                ('Campo', models.CharField(max_length=200)),
                ('fk_NODE_Node_nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.node')),
            ],
        ),
        migrations.RemoveField(
            model_name='pool_membro',
            name='fk_NODE_node_membro',
        ),
        migrations.AddField(
            model_name='pool',
            name='fk_POOL_MEMBRO_Nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.pool_membro'),
        ),
        migrations.AddField(
            model_name='pool_membro',
            name='fk_NODE_Node_nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.node'),
        ),
        migrations.CreateModel(
            name='Virtual_Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('virtual_server_name', models.CharField(max_length=200)),
                ('mask', models.CharField(max_length=200)),
                ('porta', models.CharField(max_length=200)),
                ('fk_Nome_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.pool')),
                ('fk_virtual_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.virtual_address')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster_Big',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nome_cluster', models.CharField(max_length=200)),
                ('fk_NETBOX_Device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.device')),
                ('fk_NODE_Node_nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.node')),
                ('fk_VIRTUAL_SERVER_virtual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigipnetbox.virtual_server')),
            ],
        ),
    ]
