# Generated by Django 4.0.6 on 2022-08-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigipnetbox', '0002_virtual_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AlterModelOptions(
            name='pool',
            options={'ordering': ['Nome_pool']},
        ),
        migrations.AlterModelOptions(
            name='pool_membro',
            options={'ordering': ['nome_membro']},
        ),
    ]
