# Generated by Django 4.0.6 on 2022-09-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigipnetbox', '0002_remove_clusterf5_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusterf5',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='devicef5',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='irule',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='partition',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pool',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='poolmember',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='virtualserver',
            options={'ordering': ['name']},
        ),
    ]
