# Generated by Django 4.0.6 on 2022-09-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigipnetbox', '0003_alter_clusterf5_options_alter_devicef5_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusterf5',
            options={'ordering': ['name'], 'verbose_name': 'Cluster', 'verbose_name_plural': 'Clusters'},
        ),
        migrations.AlterModelOptions(
            name='devicef5',
            options={'ordering': ['name'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='irule',
            options={'ordering': ['name'], 'verbose_name': 'Irule', 'verbose_name_plural': 'Irules'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['name'], 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AlterModelOptions(
            name='partition',
            options={'ordering': ['name'], 'verbose_name': 'Partition', 'verbose_name_plural': 'Partitions'},
        ),
        migrations.AlterModelOptions(
            name='pool',
            options={'ordering': ['name'], 'verbose_name': 'Pool', 'verbose_name_plural': 'Pools'},
        ),
        migrations.AlterModelOptions(
            name='poolmember',
            options={'ordering': ['name'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='virtualserver',
            options={'ordering': ['name'], 'verbose_name': 'Virtual Server', 'verbose_name_plural': 'Virtual Servers'},
        ),
        migrations.AlterField(
            model_name='poolmember',
            name='node_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to='bigipnetbox.node'),
        ),
        migrations.AlterField(
            model_name='poolmember',
            name='pool_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='bigipnetbox.pool'),
        ),
    ]
